### ISSUE TITLE
GetMedata() returns 404 for custom metadata keys

### ISSUE THREAD

**Issue by wonderfly** [GoogleCloudPlatform/compute-image-packages#366]
My instance has a custom instance key, `key`, and I am able to get its value using `curl`:

```
curl "http://metadata.google.internal/computeMetadata/v1/instance/attributes/key?timeout_sec=60&last_etag=0&alt=json&recursive=True&wait_for_change=False" -H "Metadata-Flavor: Google"
```

But if I use the `metadata watcher` Python library, e.g., `watcher.GetMedatadata(metadata_key='instance/attributes/key')`, I get:

```
ERROR:root:GET request error retrieving metadata. HTTP Error 404: Not Found.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/google_compute_engine/metadata_watcher.py", line 158, in _HandleMetadataUpdate
    metadata_key=metadata_key, recursive=recursive, wait=wait)
  File "/usr/lib64/python2.7/site-packages/google_compute_engine/metadata_watcher.py", line 134, in _GetMetadataUpdate
    response = self._GetMetadataRequest(metadata_url, params=params)
  File "/usr/lib64/python2.7/site-packages/google_compute_engine/metadata_watcher.py", line 50, in Wrapper
    response = func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/google_compute_engine/metadata_watcher.py", line 97, in _GetMetadataRequest
    return request_opener.open(request, timeout=self.timeout*1.1)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
```

**Comment by illfelder** [comment]
The call to the metadata server via the MetadataWatcher should have the argument: `recursive=False` 

I'm looking into why this is not required when running curl.

**Comment by wonderfly** [comment]
Thanks, appending `recursive=False` to the `GetMetadata` call worked for me.
