### ISSUE TITLE
Can't boot from image generated by gcimagebundle

### ISSUE THREAD

**Issue by myhro** [GoogleCloudPlatform/compute-image-packages#72]
I've been discussing this in private with @jkaplowitz and he suggested me to open an issue here. I've tried to do the following steps using both `projects/debian-cloud/global/images/debian-7-wheezy-v20140415` and `projects/debian-cloud/global/images/backports-debian-7-wheezy-v20140415` images:

- Start a new instance;
- Install some packages using `apt-get` and `taksel install standard`;
- Generate a new image from the current instance using `gcimagebundle -d /dev/sda -o /tmp`;
- Upload the generated image to Cloud Storage;
- Import the image using `gcutil addimage ...`;
- Start another instance using the image imported on the previous step.

The problem is that this new instance never finishes its boot process. This is what I've found looking at `gcutil getserialportoutput`:

```
May 28 02:26:00 localhost virtionet-irq-affinity: Could not set channels for eth0 to
curl for instance-id returned 7
curl for instance-id returned 7
May 28 02:26:01 localhost google: onboot initializing
curl for instance-id returned 7
curl for instance-id returned 7
curl for instance-id returned 7
curl for instance-id returned 7
curl for instance-id returned 7
curl for instance-id returned 7
curl for instance-id returned 7
Traceback (most recent call last):
  File "/usr/share/google/google_daemon/manage_accounts.py", line 87, in <module>
    options.daemon, options.debug)
  File "/usr/share/google/google_daemon/manage_accounts.py", line 62, in Main
    accounts_manager.Main()
  File "/usr/share/google/google_daemon/accounts_manager.py", line 46, in Main
    self.RegenerateKeysAndCreateAccounts()
  File "/usr/share/google/google_daemon/accounts_manager.py", line 100, in RegenerateKeysAndCreateAccounts
    self.lock_file.RunExclusively(self.lock_fname, self.CreateAccounts)
  File "/usr/share/google/google_daemon/utils.py", line 156, in RunExclusively
    method()
  File "/usr/share/google/google_daemon/accounts_manager.py", line 104, in CreateAccounts
    desired_accounts = self.desired_accounts.GetDesiredAccounts()
  File "/usr/share/google/google_daemon/desired_accounts.py", line 124, in GetDesiredAccounts
    etag=self.attributes_etag)
  File "/usr/share/google/google_daemon/desired_accounts.py", line 97, in _GetAttribute
    attribute_url, etag=etag, timeout_secs=timeout_secs)
  File "/usr/share/google/google_daemon/desired_accounts.py", line 76, in _MakeHangingGetRequest
    return self.urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 401, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 419, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1211, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1181, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 101] Network is unreachable>
```

The whole log files can be found here: https://gist.github.com/anonymous/9ed5232d23266dd7a096

**Comment by myhro** [comment]
Well, nearly a year later I finally figured out what is happening: the `tasksel install standard` task removes some core network tools. It's clear if you run it as `apt-get install $(tasksel --task-packages standard)`:

```
(...)
The following packages will be REMOVED:
  ifupdown iproute isc-dhcp-client
(...)
```

I'm closing this issue, as it's not a problem on `gcimagebundle` itself.
