### ISSUE TITLE
e6eab0c1 breaks SUSE distros

### ISSUE THREAD

**Issue by rjschwei** [GoogleCloudPlatform/compute-image-packages#844]
With #e6eab0c1 the "DisableIpv6" interface was introduced in network_setup.py. This in turn call through to distribution specific implementations. However for SUSE the interface was not implemented and it was not added to the base class either. Therefore this generates a traceback:

google-networking: ERROR Exception calling the response handler. 'Utils' object has no attribute 'DisableIpv6'.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/google_compute_engine/metadata_watcher.py", line 200, in WatchMetadata
    handler(response)
  File "/usr/lib/python2.7/site-packages/google_compute_engine/networking/network_daemon.py", line 97, in HandleNetworkInterfaces
    self.network_setup.DisableIpv6([default_interface.name])
  File "/usr/lib/python2.7/site-packages/google_compute_engine/networking/network_setup/network_setup.py", line 83, in DisableIpv6
    self.distro_utils.DisableIpv6(interfaces, self.logger)
AttributeError: 'Utils' object has no attribute 'DisableIpv6'

**Comment by zmarano** [comment]
The immediate issue was resolved- we have unresolved issues around how to implement DHCP refreshes with wicked. But that conversation is happening on the SUSE side.
